version: "3.1"
services:
    web:
        container_name: web
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - atom_default
    db:
        container_name: db
        image: mysql:8.0
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - atom_default

    lamp-redis:
        image: redis:latest
        container_name: lamp-redis
        ports:
            - "6389:6379"
        networks:
            - atom_default

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "8002:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - atom_default
volumes:
    persistent:

networks:
    atom_default:
